---
- name: Install and Configure Cockpit with Additional Modules and Network Fix
  hosts: all
  become: yes
  tasks:
    - name: Update the package manager cache
      ansible.builtin.shell: |
        if command -v apt &>/dev/null; then
          apt update -y
        elif command -v yum &>/dev/null; then
          yum update -y
        elif command -v dnf &>/dev/null; then
          dnf update -y
        else
          echo 'Unsupported package manager' && exit 1
        fi
      register: update_result
      failed_when: update_result.rc != 0

    - name: Install Cockpit
      ansible.builtin.shell: |
        if command -v apt &>/dev/null; then
          apt install cockpit -y
        elif command -v yum &>/dev/null; then
          yum install cockpit -y
        elif command -v dnf &>/dev/null; then
          dnf install cockpit -y
        else
          echo 'Unsupported package manager' && exit 1
        fi
      register: install_result
      failed_when: install_result.rc != 0

    - name: Enable and start Cockpit service
      ansible.builtin.service:
        name: cockpit
        enabled: yes
        state: started

    - name: Ensure /etc/cockpit/disallowed-users exists
      ansible.builtin.file:
        path: /etc/cockpit/disallowed-users
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Remove 'root' from /etc/cockpit/disallowed-users
      ansible.builtin.lineinfile:
        path: /etc/cockpit/disallowed-users
        regexp: '^root$'
        state: absent

    - name: Add 45Drives repository
      ansible.builtin.shell: |
        curl -sSL https://repo.45drives.com/setup | sudo bash || echo "Repo setup script exited with non-zero status"
      register: repo_setup
      failed_when: "'Exiting...' not in repo_setup.stdout"

    - name: Update package manager after adding 45Drives repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Cockpit File Sharing
      ansible.builtin.apt:
        name: cockpit-file-sharing
        state: present

    - name: Download Cockpit Navigator package
      ansible.builtin.get_url:
        url: https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb
        dest: /tmp/cockpit-navigator_0.5.10-1focal_all.deb

    - name: Install Cockpit Navigator
      ansible.builtin.shell: apt install -y /tmp/cockpit-navigator_0.5.10-1focal_all.deb
      register: navigator_install
      failed_when: navigator_install.rc != 0

    - name: Create NetworkManager configuration file
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
        content: |
          [keyfile]
          unmanaged-devices=none
        owner: root
        group: root
        mode: '0644'

    - name: Add dummy network interface
      ansible.builtin.command:
        cmd: nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24 gw4 1.2.3.1

    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 300
